[scoop]

[scoop.setup]
aria2-enabled = true
aria2-warning-enabled = false
use_lessmsi= true

[scoop.install]
prereq = ["git","aria2","lessmsi"]
bucket = ["extras","versions"]
app = [
    "bat","gsudo","less","touch","ugrep","which", # essential CLI tools
    "gh","nvm","tdm-gcc","vscode", # developement tools
    "pwsh","oh-my-posh","windows-terminal", # terminal customisation
    "7zip","authy","chromium","chrome", # productivity apps
    "imageglass","paint.net","paint.net-plugin-boltbait" # image editing
    ]

[scoop.config]
aria2-enabled = true
aria2-warning-enabled = false
use_lessmsi= true
show_manifest    = true
cat_style = "full"
alias = "@{rm=scoop-rm; i=scoop-i; v=scoop-v; ls=scoop-ls}"

[nvm]

[nvm.setup]
version = "lts"

[nvm.config]
status = "on"

[oh-my-posh]

[oh-my-posh.setup]
theme="amro"

[vscode]

[vscode.setup]
extension = [
    "ardenivanov.svelte-intellisense",
    "BriteSnow.vscode-toggle-quotes",
    "bungcip.better-toml",
    "christian-kohler.path-intellisense",
    "DavidAnson.vscode-markdownlint",
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "ext8.gruvbox-themes-1",
    "ext8.pyutils",
    "JonathanHarty.gruvbox-material-icon-theme",
    "mgesbert.python-path",
    "ms-python.python",
    "ms-python.vscode-pylance",
    "ms-vscode.cpptools",
    "njpwerner.autodocstring",
    "oderwat.indent-rainbow",
    "PKief.material-product-icons",
    "sainnhe.gruvbox-material",
    "svelte.svelte-vscode",
    "usernamehw.errorlens",
    "VisualStudioExptTeam.intellicode-api-usage-examples",
    "VisualStudioExptTeam.vscodeintellicode"
    ]

[conda]

[conda.setup]
py_version = "^3.10.0"